micronaut:
  application:
    name: veiculoService
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/dbveiculos
    driverClassName: org.postgresql.Driver
    username: postgres
    password: '123456'
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    packages-to-scan:
      - 'br.com.curso.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true

netty:
  default:
    allocator:
      max-order: 3
